/*
 * This file is generated by jOOQ.
 */
package db.tables.records;


import db.tables.UserPermission;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPermissionRecord extends UpdatableRecordImpl<UserPermissionRecord> implements Record4<Long, Long, LocalDateTime, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_permission.permission_id</code>.
     */
    public void setPermissionId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_permission.permission_id</code>.
     */
    public Long getPermissionId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_permission.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_permission.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.user_permission.created_on</code>.
     */
    public void setCreatedOn(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_permission.created_on</code>.
     */
    public LocalDateTime getCreatedOn() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.user_permission.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_permission.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, LocalDateTime, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, Long, LocalDateTime, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserPermission.USER_PERMISSION.PERMISSION_ID;
    }

    @Override
    public Field<Long> field2() {
        return UserPermission.USER_PERMISSION.USER_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return UserPermission.USER_PERMISSION.CREATED_ON;
    }

    @Override
    public Field<String> field4() {
        return UserPermission.USER_PERMISSION.CREATED_BY;
    }

    @Override
    public Long component1() {
        return getPermissionId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public LocalDateTime component3() {
        return getCreatedOn();
    }

    @Override
    public String component4() {
        return getCreatedBy();
    }

    @Override
    public Long value1() {
        return getPermissionId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public LocalDateTime value3() {
        return getCreatedOn();
    }

    @Override
    public String value4() {
        return getCreatedBy();
    }

    @Override
    public UserPermissionRecord value1(Long value) {
        setPermissionId(value);
        return this;
    }

    @Override
    public UserPermissionRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserPermissionRecord value3(LocalDateTime value) {
        setCreatedOn(value);
        return this;
    }

    @Override
    public UserPermissionRecord value4(String value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public UserPermissionRecord values(Long value1, Long value2, LocalDateTime value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserPermissionRecord
     */
    public UserPermissionRecord() {
        super(UserPermission.USER_PERMISSION);
    }

    /**
     * Create a detached, initialised UserPermissionRecord
     */
    public UserPermissionRecord(Long permissionId, Long userId, LocalDateTime createdOn, String createdBy) {
        super(UserPermission.USER_PERMISSION);

        setPermissionId(permissionId);
        setUserId(userId);
        setCreatedOn(createdOn);
        setCreatedBy(createdBy);
        resetChangedOnNotNull();
    }
}
