/*
 * This file is generated by jOOQ.
 */
package db;


import org.jooq.Sequence;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.permission_seq</code>
     */
    public static final Sequence<Long> PERMISSION_SEQ = Internal.createSequence("permission_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, 50, null, null, false, null);

    /**
     * The sequence <code>public.role_seq</code>
     */
    public static final Sequence<Long> ROLE_SEQ = Internal.createSequence("role_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, 50, null, null, false, null);

    /**
     * The sequence <code>public.user_seq</code>
     */
    public static final Sequence<Long> USER_SEQ = Internal.createSequence("user_seq", Public.PUBLIC, SQLDataType.BIGINT.nullable(false), null, 50, null, null, false, null);
}
