/*
 * This file is generated by jOOQ.
 */
package db;


import db.tables.Permission;
import db.tables.Role;
import db.tables.User;
import db.tables.UserPermission;
import db.tables.UserRole;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.permission</code>.
     */
    public static final Permission PERMISSION = Permission.PERMISSION;

    /**
     * The table <code>public.role</code>.
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>public.user_permission</code>.
     */
    public static final UserPermission USER_PERMISSION = UserPermission.USER_PERMISSION;

    /**
     * The table <code>public.user_role</code>.
     */
    public static final UserRole USER_ROLE = UserRole.USER_ROLE;
}
