version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    ports:
      - '5432:5432'
    volumes:
      - D:/dockerfiles/postgres/db-data:/var/lib/postgresql/data
volumes:
  db:
    driver: local